let myDishes = [
    {
        "name": "TOM KHA",
        "price": 6.90,
        "description": "Kokos-Galgant-Suppe",
        "incredients": "Zitronengras, Limettenblätter, Chili, Austernpilze",
    },
    {
        "name": "TOM YAM",
        "price": 6.90,
        "description": "Scharf-saure Suppe",
        "incredients": "Zitronengras, Limettenblätter, Galgant, Thai-Chili Paste, Chili",
    },
    {
        "name": "TOM YAM TALE",
        "price": 9.50,
        "description": "Meeresfrüchte-Suppe",
        "incredients": "Thai-Chilipaste, Austernpilze, Tomaten, Zwiebeln, Galgant, Zitronengras, KaffirLimettenblätter, Thai-Koriander, Chili - scharf",
    },
    {
        "name": "TOM JÜD WUN SEN",
        "price": 6.90,
        "description": "Glasnudelsuppe",
        "incredients": "Kohl, Karotten, Mu-Err-Pilze, Koriander",
    },
    {
        "name": "SOM TAM",
        "price": 13.50,
        "description": "Thai-Papapya-Salat",
        "incredients": "Unreife Papaya-Streifen, Knoblauch, Chili, Limette, Erdnüsse",
    },
    {
        "name": "YAM WUN SEN",
        "price": 14.50,
        "description": "Glasnudelsalat mit Garnelen",
        "incredients": "Mu-Err-Pilze, Zwiebeln, Sellerie, Koriander, Tomate, Chili, Erdnüsse",
    },
    {
        "name": "LAAB",
        "price": 13.90,
        "description": "Schweinehack Salat",
        "incredients": "Zitronengras, Minze, Koriander, Limettenblätter, Chili, geröstete Reiskörner",
    },
    {
        "name": "GÄNG PED",
        "price": 16.50,
        "description": "Rotes Curry",
        "incredients": "Thai-Basilikum, Bambus, Aubergine, Bohnen, Zucchini, Paprika - leicht scharfe Version",
    },
    {
        "name": "GÄNG KIAO WAAN",
        "price": 16.50,
        "description": "Grünes Curry",
        "incredients": "Thai-Basilikum, Bambus, Aubergine, Bohnen, Zucchini, Paprika - mittel scharfe Version",
    },
    {
        "name": "GÄNG PED PED YANG",
        "price": 16.50,
        "description": "Ananas Curry",
        "incredients": "Thai-Basilikum, Bambus, Aubergine, Bohnen, Tomate, Zucchini, Paprika - leicht scharf",
    },
    {
        "name": "PAD KRAPAO",
        "price": 16.90,
        "description": "Schweinehack mit Thai-Basilikum",
        "incredients": "Knoblauch, Chili, Zwiebel, Bohnen",
    },
    {
        "name": "PAD PRIG GÄNG ",
        "price": 18.90,
        "description": "Garnelen mit Currypaste",
        "incredients": "Limettenblätter, Zwiebel, Bambus, Bohnen, Paprika",
    },
    {
        "name": "PAD MED MAMUANG",
        "price": 16.50,
        "description": "Tofu mit Cashewkernen",
        "incredients": "Thai-Chilipaste, Knoblauch, Zwiebel, Paprika, Champignon, Bambu",
    },
    {
        "name": "PAD THAI",
        "price": 15.50,
        "description": "Gebratene Thai-Reisnudeln",
        "incredients": "Reisnudeln mit Ei, Tofu, Lauch, Sprossen, Erdnüsse in hauseigener Sauce auf fruchtiger Tamarinden-Basis gekocht",
    },
    {
        "name": "PAD MIE LÜANG",
        "price": 14.90,
        "description": "Gebratene Nudeln",
        "incredients": "mit Ei, Knoblauch, Kohl, Brokkoli, Karotte, Champignon, Sprossen",
    },
    {
        "name": "KAO PAD",
        "price": 14.90,
        "description": "Gebratener Reis",
        "incredients": "mit Karotte, Ei, Brokkoli, Lauchzwiebel, Tomate ",
    },
    {
        "name": "THAI STYLE SUKIYAKI",
        "price": 16.90,
        "description": "Glasnudeln Gebraten Sukiyaki",
        "incredients": "Sprossen, Chinakohl, Lauch, Sellerie, Sesam, Erdnuss, Limette",
    },
    {
        "name": "KAO NIAO MAMUANG",
        "price": 7.90,
        "description": "Kokos-Klebreis mit Mango",
        "incredients": "Mango, Erdnüsse",
    },
    {
        "name": "KAHNOM TOM",
        "price": 6.50,
        "description": "Reismehlbällchen mit Kokosfüllung",
        "incredients": "in Kokosmilch",
    },
    {
        "name": "GLUAI TORD mit Eis",
        "price": 6.90,
        "description": "Gebackene Banane - mit Vanilleeis",
        "incredients": "Sesam, Kokosflocken, Honig",
    },
]